### ISSUE TITLE
Profile password type incorrect in pop-up

### ISSUE THREAD

**Issue by JeremyWW** [greizgh/Phashword#22]
Thought I'd raised this somewhere but clearly not. If I create a new profile in Settings and assign it the password type 'Alphanumeric' as opposed to the default 'Alphanumeric and special chars' the correct password type as assigned in the profile is not used in the pop-up thus the wrong password is generated.

EDIT: Just discovered the same applies to password length. Maybe the same for the private key as well but I haven't tested that.

**Comment by greizgh** [comment]
I was able to reproduce it with password length and type, but private key is correctly handled.
This is somewhat expected behavior: for stored site profiles (not the one you edit private key), we also keep track of preferences (see #16).
The unexpected part is: we store way too much site profiles, event those for which no password was ever created.
Thanks for noticing that, I'll work on it.

**Comment by JeremyWW** [comment]
Not sure I understand that.  Surely if you define a profile,  including 
password length and type,  in Settings those parameters should appear when 
you choose the same profile from the pop-up.
____

**Comment by JeremyWW** [comment]
EDIT: Which is the way Twik behaves in Chrome...
____

Sent from my phone



Not sure I understand that.  Surely if you define a profile,  including
password length and type,  in Settings those parameters should appear when
you choose the same profile from the pop-up.
____

**Comment by greizgh** [comment]
That should be fixed with version 2.0.1
