### ISSUE TITLE
Firefox 79 breaks this addon

### ISSUE THREAD

**Issue by HerrBert233** [greizgh/Phashword#29]
Hi,

I just upgraded to Firefox 79 and realized that Phashword lost all its settings. Everything was back to default.

The settings were still present, I downgraded to Firefox 78 ESR than and could still find all my settings in the profile.

There seems to be an issue with reading / writing the settings, changes API or storage location or something. It would be great if this addon could work again.

Windows 10 / Firefox 79 x64

Herbert

**Comment by greizgh** [comment]
Hello,

Thanks for taking the time to report this issue.
This may be related:
> New rust-based storage.sync implementation enabled by default in Firefox 79

That being said, this webextension hasn't seen any movement since 2017, I'm not using it and so do not plan on maintaining it any further.
I'm sorry about your experience, the best advice I can offer you is:

- either use a more featured, password management tool, such as [bitwarden](https://bitwarden.com/) (open source as well)
- switch over a similar password generator, but maintained: [lesspass](https://lesspass.com/#/)
